version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: locadoraDB
    ports:
      - "5432:5432" # expõe para o Hibernate no host
    networks:
      - postgres_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "15432:80" # porta para acessar o pgAdmin pelo navegador
    networks:
      - postgres_network

networks:
  postgres_network:
    driver: bridge